import { StyleSheet } from 'react-native';

export default StyleSheet.create({
	buttonContainer: {
		backgroundColor: '#ffffff',
		borderRadius: 35,
		paddingVertical: 10,
		marginHorizontal: 32,
		marginVertical: 16,
		elevation: 2,
	},
	buttonText: {
		fontFamily: 'Montserrat_500Medium',
		fontSize: 18,
		color: '#31C7E6',
		alignSelf: 'center',
	},
	mainText: {
		fontFamily: 'Montserrat_500Medium',
		fontSize: 40,
		alignSelf: 'center',
		color: '#FFFFFF',
		marginTop: 150,
	},
	secondaryText: {
		fontFamily: 'Montserrat_500Medium',
		fontSize: 20,
		alignSelf: 'center',
		color: '#FFFFFF',
		marginRight: 32,
		marginLeft: 32,
		textAlign: 'center',
		marginTop: 100,
	},
	pageDots: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		marginHorizontal: 150,
		marginVertical: 16,
	},
	circleFill: {
		elevation: 2,
		width: 15,
		height: 15,
		borderRadius: 10,
		backgroundColor: '#FFFFFF',
	},
	circleEmpty: {
		elevation: 2,
		width: 15,
		height: 15,
		borderRadius: 10,
		backgroundColor: '#41D4E8',
		borderColor: '#FFFFFF',
		borderWidth: 2,
	},
	whiteCardContainer: {
		display: 'flex',
		flexShrink: 1,
	},
	whiteCard: {
		backgroundColor: '#FFFFFF',
		borderRadius: 16,
		padding: 16,
		marginHorizontal: 16,
		marginVertical: 16,
	},
	whiteCardText: {
		fontFamily: 'Montserrat_500Medium',
		fontSize: 18,
		marginBottom: 16,
	},
	whiteCardButton: {
		backgroundColor: '#FFFFFF',
		borderRadius: 14,
		borderColor: '#04A0E1',
		borderWidth: 3,
		padding: 6,
		marginRight: 8,
		marginBottom: 8,
	},
	whiteCardButtonSelected: {
		backgroundColor: '#04A0E1',
		borderRadius: 14,
		borderColor: '#04A0E1',
		borderWidth: 3,
		padding: 6,
		marginRight: 8,
		marginBottom: 8,
	},
	whiteCardButtonText: {
		fontFamily: 'Montserrat_500Medium',
		fontSize: 16,
		alignSelf: 'center',
		color: '#000000',
	},
	whiteCardButtonTextSelected: {
		fontFamily: 'Montserrat_500Medium',
		fontSize: 16,
		alignSelf: 'center',
		color: '#ffffff',
	},
	whiteCardGroupButton: {
		backgroundColor: '#FFFFFF',
		borderRadius: 14,
		borderColor: '#04A0E1',
		borderWidth: 3,
		marginVertical: 50,
		padding: 5,
		marginHorizontal: 20,
	},
	whiteCardGroupText: {
		fontFamily: 'Montserrat_500Medium',
		fontSize: 16,
		color: '#00000044',
	},
	whiteCardGroupIcon: {
		color: '#00000044',
		position: 'absolute',
		right: 6,
		top: 4,
		bottom: 0,
	},
});
